repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/thlorenz/doctoc
  rev: v1.4.0
  hooks:
    - id: doctoc
      args: [--notitle, --maxlevel=5]
